# Generated by Django 4.2.10 on 2024-04-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_catagory',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-veg', 'Non-veg'), ('Drinks', 'Drinks')], default='Veg', max_length=10),
        ),
    ]
